CREATE TABLE users (
  ID VARCHAR(255) PRIMARY KEY,
  Email VARCHAR(50) NOT NULL,
  Password VARCHAR(50) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMP DEFAULT NULL
);